import os
import time
import logging
import json
from pathlib import Path
from contextlib import asynccontextmanager
from fastapi import FastAPI, HTTPException, status
from pydantic import BaseModel, Field
import google.generativeai as genai
from google.api_core import exceptions
from dotenv import load_dotenv
import chromadb

# 1. Global Configuration
env_path = Path(__file__).parent / ".env"
load_dotenv(dotenv_path=env_path, override=True)

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s"
)
logger = logging.getLogger("rag_backend")

# Configure Gemini API Key globally
api_key = os.getenv("GEMINI_API_KEY")
EMBED_MODEL = os.getenv("GEMINI_EMBED_MODEL", "models/gemini-embedding-001")
GEMINI_MODEL = os.getenv("GEMINI_MODEL", "gemini-2.5-flash")

if not api_key or api_key == "your_gemini_api_key_here":
    logger.critical("GEMINI_API_KEY is not set or using placeholder in .env file.")
else:
    genai.configure(api_key=api_key)

# Global variables for ChromaDB
chroma_client = None
collection = None

# 2. Database Ingestion & Lifespan Setup
@asynccontextmanager
async def lifespan(app: FastAPI):
    global chroma_client, collection
    
    if not api_key or api_key == "your_gemini_api_key_here":
        logger.critical("GEMINI_API_KEY is missing. Ingestion skipped.")
        yield
        return
        
    try:
        # Step A: Load documents from external documents.json
        json_path = Path(__file__).parent / "documents.json"
        if not json_path.exists():
            logger.error(f"documents.json not found at: {json_path.absolute()}")
            yield
            return
            
        with open(json_path, "r", encoding="utf-8") as f:
            ml_documents = json.load(f)
            
        # Step B: Initialize Local Persistent ChromaDB Client
        db_path = Path(__file__).parent / "chroma_db"
        logger.info(f"Initializing persistent ChromaDB client at: {db_path.absolute()}")
        chroma_client = chromadb.PersistentClient(path=str(db_path.absolute()))
        
        # Step C: Get or Create 'rag_docs' Collection
        collection = chroma_client.get_or_create_collection(
            name="rag_docs",
            metadata={"hnsw:space": "cosine"}
        )
        
        # Step D: Ingestion & Indexing (only if collection is empty)
        doc_count = collection.count()
        if doc_count == 0:
            logger.info("ChromaDB collection is empty. Generating embeddings and ingesting documents...")
            ids, documents, metadatas, embeddings = [], [], [], []
            
            for doc in ml_documents:
                # Prepare metadata
                meta = {
                    "title": doc["title"],
                    "source": doc["source"],
                    "category": doc["category"],
                    "keywords": ", ".join(doc["keywords"])
                }
                # Step E: Generate embeddings using task_type="retrieval_document"
                res = genai.embed_content(
                    model=EMBED_MODEL,
                    content=doc["content"],
                    task_type="retrieval_document"
                )
                embeddings.append(res["embedding"])
                ids.append(doc["id"])
                documents.append(doc["content"])
                metadatas.append(meta)
                
            # Insert into ChromaDB collection
            collection.add(
                ids=ids,
                embeddings=embeddings,
                documents=documents,
                metadatas=metadatas
            )
            logger.info(f"Successfully ingested {len(ids)} documents into ChromaDB.")
        else:
            logger.info(f"ChromaDB collection 'rag_docs' already initialized with {doc_count} documents. Skipping ingestion.")
            
    except exceptions.GoogleAPICallError as e:
        logger.critical(f"Google Gemini API error during startup ingestion: {e}")
    except Exception as e:
        logger.critical(f"Unexpected error during startup: {e}")
        
    yield

app = FastAPI(
    title="RAG Backend Service",
    description="FastAPI service combining ChromaDB and Gemini API for Retrieval-Augmented Generation",
    version="1.0.0",
    lifespan=lifespan
)

# 3. Request & Response Schemas
class RagRequest(BaseModel):
    query: str = Field(..., description="The user query to be answered using retrieval context", min_length=1)

class RagResponse(BaseModel):
    query: str = Field(..., description="The original search query")
    context_used: list[str] = Field(..., description="List of document texts retrieved as context")
    final_answer: str = Field(..., description="The contextual response generated by the LLM")

# 4. Endpoints
@app.post("/api/rag", response_model=RagResponse)
async def perform_rag(request: RagRequest):
    global collection
    
    if not collection:
        logger.error("RAG failed: ChromaDB collection 'rag_docs' is not initialized.")
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail="Vector database or API has not been initialized. Please configure GEMINI_API_KEY."
        )
        
    query = request.query
    logger.info(f"Incoming RAG Request - Query: {query}")
    
    start_time = time.time()
    try:
        # ==========================================
        # STEP 1: RETRIEVAL (Query Embedding + Vector Search)
        # ==========================================
        # 1a. Embed user query using task_type="retrieval_query"
        embed_start = time.time()
        embed_res = genai.embed_content(
            model=EMBED_MODEL,
            content=query,
            task_type="retrieval_query"
        )
        query_embedding = embed_res["embedding"]
        embed_duration = time.time() - embed_start
        
        # 1b. Search ChromaDB for top 3 matching contexts
        db_start = time.time()
        db_results = collection.query(
            query_embeddings=[query_embedding],
            n_results=3
        )
        db_duration = time.time() - db_start
        
        context_docs = []
        if db_results and db_results["documents"]:
            context_docs = db_results["documents"][0]
            
        if not context_docs:
            logger.warning(f"No context documents found for query: {query}")
            context_docs = ["No relevant context found in database."]
            
        # ==========================================
        # STEP 2: AUGMENTATION (Construct Prompt Template)
        # ==========================================
        # Exact prompt structure as requested in assessment guidelines
        context_text = "\n".join(context_docs)
        prompt = (
            "Use the following context to answer the question:\n"
            f"Context:\n{context_text}\n"
            f"Question:\n{query}\n"
            "Answer based on the context:"
        )
        
        # ==========================================
        # STEP 3: GENERATION (Generate Grounded Answer)
        # ==========================================
        llm_start = time.time()
        model = genai.GenerativeModel(
            model_name=GEMINI_MODEL,
            system_instruction="You are a helpful and concise assistant. Answer questions strictly based on the provided context. If the answer cannot be found in the context, clearly state that the context does not contain enough information."
        )
        llm_res = model.generate_content(prompt)
        final_answer = llm_res.text.strip()
        llm_duration = time.time() - llm_start
        
        total_duration = time.time() - start_time
        logger.info(
            f"RAG Request completed in {total_duration:.2f}s | "
            f"Embed: {embed_duration:.2f}s | DB Query: {db_duration:.2f}s | LLM: {llm_duration:.2f}s"
        )
        
        return RagResponse(
            query=query,
            context_used=context_docs,
            final_answer=final_answer
        )
        
    # Consolidated exception blocks
    except exceptions.InvalidArgument as e:
        logger.error(f"Invalid Argument error: {e}")
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=f"Gemini API parameter error: {str(e)}"
        )
    except (exceptions.Unauthenticated, exceptions.PermissionDenied) as e:
        logger.error(f"Authentication/Permission error: {e}")
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Gemini API authentication failed. Verify your GEMINI_API_KEY."
        )
    except exceptions.ResourceExhausted as e:
        logger.error(f"Rate Limit error: {e}")
        raise HTTPException(
            status_code=status.HTTP_429_TOO_MANY_REQUESTS,
            detail="Gemini API rate limit exceeded."
        )
    except Exception as e:
        logger.error(f"Unexpected error during RAG process: {e}")
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"An unexpected internal error occurred: {str(e)}"
        )

@app.get("/health")
async def health_check():
    key_configured = api_key is not None and api_key != "your_gemini_api_key_here"
    db_initialized = collection is not None
    doc_count = collection.count() if db_initialized else 0
    return {
        "status": "healthy",
        "api_key_configured": key_configured,
        "database_initialized": db_initialized,
        "document_count": doc_count
    }
